// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmC0PcOkv9rCTOpd5nUz1RxguapEj2HwM',
    appId: '1:91496852614:android:62c105902ffd04508c7507',
    messagingSenderId: '91496852614',
    projectId: 'my-trivy',
    databaseURL: 'https://my-trivy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-trivy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8R8xrcHj_oIC4TgHC0Y4ctSZhiYzzFM',
    appId: '1:91496852614:ios:42aaceabb3011ea48c7507',
    messagingSenderId: '91496852614',
    projectId: 'my-trivy',
    databaseURL: 'https://my-trivy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-trivy.appspot.com',
    iosClientId: '91496852614-0uudf7c1gleaaiohr859vi0okt8pg77e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTrivy',
  );
}
